(function(){
    'use strict';
    var DEFAULT_URL='https://iptv-live-merge.phuongnm7-iptv.workers.dev/playlist.m3u';
    var state={channels:[],filtered:[],section:'all',group:'',playing:-1,overlay:true,retries:0,showUrls:false};
    var $=function(id){return document.getElementById(id);};
    var focusables=function(scope){return Array.prototype.slice.call((scope||document).querySelectorAll('.focusable:not(.hidden)')).filter(function(x){return x.offsetWidth>0&&x.offsetHeight>0;});};
    function save(key,value){try{localStorage.setItem('nm7.'+key,JSON.stringify(value));}catch(e){}}
    function load(key,fallback){try{var value=localStorage.getItem('nm7.'+key);return value?JSON.parse(value):fallback;}catch(e){return fallback;}}
    function toast(text){$('toast').textContent=text;$('toast').className='show';setTimeout(function(){$('toast').className='';},1800);}
    function escapeText(text){return String(text||'').replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
    function xhr(url,ok,fail){var x=new XMLHttpRequest();x.open('GET',url,true);x.timeout=25000;x.onreadystatechange=function(){if(x.readyState===4){if(x.status>=200&&x.status<300)ok(x.responseText,x.responseURL||url);else fail('HTTP '+x.status);}};x.ontimeout=function(){fail('Hết thời gian kết nối');};x.onerror=function(){fail('Không tải được nguồn');};x.send();}
    function loadPlaylist(url){$('loading').className='loading';$('empty').className='empty hidden';xhr(url,function(text){var result=Nm7M3u.parse(text);if(!result.channels.length){toast('Playlist không có kênh hợp lệ');return;}$('loading').className='loading hidden';state.channels=result.channels;save('channels',state.channels);save('lastSource',url);rememberSource(url);buildGroups();filter();},function(error){$('loading').className='loading hidden';var cached=load('channels',[]);if(cached.length){state.channels=cached;buildGroups();filter();toast('Đang dùng danh sách đã lưu');}else toast(error);});}
    function rememberSource(url){var list=load('sources',[]),i;for(i=0;i<list.length;i++)if(list[i]===url)return;list.unshift(url);save('sources',list.slice(0,10));}
    function buildGroups(){var seen={},groups=[''],i,g,box=$('groups');for(i=0;i<state.channels.length;i++){g=state.channels[i].group;if(!seen[g]){seen[g]=1;groups.push(g);}}box.innerHTML='';for(i=0;i<groups.length;i++){(function(value){var b=document.createElement('button');b.className='focusable'+(state.group===value?' active':'');b.textContent=value||'Tất cả nhóm';b.onclick=function(){state.group=value;buildGroups();filter();};box.appendChild(b);}(groups[i]));}}
    function isFavorite(c){return load('favorites',[]).indexOf(c.url)>=0;}
    function filter(){var q=$('searchInput').value.toLowerCase(),recent=load('recent',[]);state.filtered=state.channels.filter(function(c){if(state.group&&c.group!==state.group)return false;if(state.section==='favorites'&&!isFavorite(c))return false;if(state.section==='recent'&&recent.indexOf(c.url)<0)return false;return !q||c.name.toLowerCase().indexOf(q)>=0||c.group.toLowerCase().indexOf(q)>=0;});if(state.section==='recent')state.filtered.sort(function(a,b){return recent.indexOf(a.url)-recent.indexOf(b.url);});renderChannels();}
    function renderChannels(){var box=$('channelGrid'),i,c,b;box.innerHTML='';$('empty').className=state.filtered.length?'empty hidden':'empty';for(i=0;i<state.filtered.length;i++){c=state.filtered[i];b=document.createElement('button');b.className='channel-card focusable';b.setAttribute('data-index',i);b.innerHTML=(c.logo?'<img src="'+escapeText(c.logo)+'">':'')+'<span class="channel-info"><span class="channel-name">'+escapeText(c.name)+'</span><br><span class="channel-group">'+escapeText(c.group)+'</span>'+(state.showUrls?'<br><span class="channel-url">'+escapeText(c.url)+'</span>':'')+'</span><span class="star">'+(isFavorite(c)?'★':'☆')+'</span>';b.onclick=(function(index){return function(){play(index);};}(i));box.appendChild(b);}}
    function activePlayer(){return window.webapis&&webapis.avplay;}
    function play(index){var c=state.filtered[index];if(!c)return;state.playing=state.channels.indexOf(c);addRecent(c.url);$('home').className='screen';$('playerScreen').className='screen player-screen active';$('playerTitle').textContent=c.name;$('playerError').className='dialog hidden';state.overlay=true;showOverlay();openPlayer(c);}
    function openPlayer(c){var p;try{p=activePlayer();if(!p)throw new Error('AVPlay chỉ hoạt động trên TV Samsung hoặc emulator Tizen');try{if(p.getState()!=='NONE')p.close();}catch(ignore){}p.open(c.url);p.setDisplayRect(0,0,1920,1080);p.setListener({onbufferingstart:function(){$('playerStatus').textContent='Đang tải luồng…';},onbufferingprogress:function(v){$('playerStatus').textContent='Đang tải '+v+'%';},onbufferingcomplete:function(){$('playerStatus').textContent='Đang phát';state.retries=0;},onstreamcompleted:function(){retryStream('Luồng đã kết thúc');},oncurrentplaytime:function(){},onerror:function(e){retryStream('Lỗi phát: '+e);},onevent:function(){},onsubtitlechange:function(){},ondrmevent:function(){}});p.prepareAsync(function(){p.play();$('playerStatus').textContent='Đang phát';},function(e){retryStream('Không chuẩn bị được luồng: '+e);});}catch(e){showPlayerError(e.message||String(e));}}
    function retryStream(reason){if(state.retries<4){state.retries++;$('playerStatus').textContent=reason+' • nối lại lần '+state.retries;setTimeout(function(){openPlayer(state.channels[state.playing]);},Math.min(8000,1000*Math.pow(2,state.retries-1)));}else showPlayerError(reason);}
    function showPlayerError(text){$('playerErrorText').textContent=text;$('playerError').className='dialog';$('retryButton').focus();}
    function stopPlayer(){try{var p=activePlayer();if(p&&p.getState()!=='NONE')p.close();}catch(e){}$('playerScreen').className='screen player-screen';$('home').className='screen active';filter();setTimeout(function(){var cards=$('channelGrid').querySelectorAll('.channel-card');if(cards.length)cards[0].focus();},0);}
    function addRecent(url){var list=load('recent',[]),i=list.indexOf(url);if(i>=0)list.splice(i,1);list.unshift(url);save('recent',list.slice(0,100));}
    function showOverlay(){state.overlay=true;$('playerOverlay').className='';$('playerShade').className='';$('playerBack').focus();}
    function hideOverlay(){state.overlay=false;$('playerOverlay').className='hidden';$('playerShade').className='hidden';}
    function showQuick(){var box=$('quickList'),i,c,b;box.innerHTML='';for(i=0;i<state.channels.length;i++){c=state.channels[i];b=document.createElement('button');b.className='focusable';b.textContent=c.name;b.onclick=(function(channelIndex){return function(){$('quickPanel').className='quick-panel hidden';state.playing=channelIndex;openPlayer(state.channels[channelIndex]);};}(i));box.appendChild(b);}$('quickPanel').className='quick-panel';if(box.firstChild)box.firstChild.focus();}
    function closeTopDialog(){var ids=['sourceDialog','sourcesDialog','settingsDialog'];for(var i=0;i<ids.length;i++)if($(ids[i]).className.indexOf('hidden')<0){$(ids[i]).className='dialog hidden';$('addButton').focus();return true;}return false;}
    function moveFocus(key){var list=focusables(),current=list.indexOf(document.activeElement),next;if(current<0){if(list[0])list[0].focus();return;}var a=document.activeElement.getBoundingClientRect(),best=1e12,i,b,dx,dy,score;for(i=0;i<list.length;i++){if(i===current)continue;b=list[i].getBoundingClientRect();dx=(b.left+b.width/2)-(a.left+a.width/2);dy=(b.top+b.height/2)-(a.top+a.height/2);if(key===37&&dx>=-5||key===39&&dx<=5||key===38&&dy>=-5||key===40&&dy<=5)continue;score=(key===37||key===39)?Math.abs(dx)+Math.abs(dy)*3:Math.abs(dy)+Math.abs(dx)*3;if(score<best){best=score;next=list[i];}}if(next)next.focus();}
    function onKey(e){var k=e.keyCode;if(k>=37&&k<=40){if($('playerScreen').className.indexOf('active')>=0&&!state.overlay&&$('quickPanel').className.indexOf('hidden')>=0){if(k===37){showQuick();return;}if(k===38||k===40){state.playing=(state.playing+(k===38?1:-1)+state.channels.length)%state.channels.length;openPlayer(state.channels[state.playing]);return;}}moveFocus(k);e.preventDefault();return;}if(k===13&&$('playerScreen').className.indexOf('active')>=0&&!state.overlay){showOverlay();return;}if(k===10009||k===27){if(closeTopDialog())return;if($('quickPanel').className.indexOf('hidden')<0){$('quickPanel').className='quick-panel hidden';return;}if($('playerScreen').className.indexOf('active')>=0){if(state.overlay){hideOverlay();return;}stopPlayer();return;}try{tizen.application.getCurrentApplication().exit();}catch(ignore){}return;}if(k===415)try{activePlayer().play();}catch(ignore2){}if(k===19)try{activePlayer().pause();}catch(ignore3){}}
    function bind(){document.addEventListener('keydown',onKey);$('searchInput').oninput=filter;$('clearButton').onclick=function(){$('searchInput').value='';state.group='';buildGroups();filter();};$('addButton').onclick=function(){$('sourceInput').value='';$('sourceDialog').className='dialog';$('sourceInput').focus();};$('cancelSource').onclick=function(){$('sourceDialog').className='dialog hidden';};$('loadButton').onclick=function(){var url=$('sourceInput').value.trim();if(!/^https?:\/\//i.test(url)){toast('URL phải bắt đầu bằng http:// hoặc https://');return;}$('sourceDialog').className='dialog hidden';loadPlaylist(url);};$('sourcesButton').onclick=showSources;$('closeSources').onclick=function(){$('sourcesDialog').className='dialog hidden';};$('settingsButton').onclick=function(){$('settingsDialog').className='dialog';$('toggleUrls').focus();};$('closeSettings').onclick=function(){$('settingsDialog').className='dialog hidden';};$('toggleUrls').onclick=function(){state.showUrls=!state.showUrls;save('showUrls',state.showUrls);$('toggleUrls').textContent=state.showUrls?'Ẩn URL trong danh sách':'Hiện URL trong danh sách';filter();};$('clearRecent').onclick=function(){save('recent',[]);toast('Đã xóa lịch sử');if(state.section==='recent')filter();};$('aboutButton').onclick=function(){toast('Nm7 IPTV cho Samsung Tizen TV 0.1.0');};$('playerBack').onclick=stopPlayer;$('retryButton').onclick=function(){state.retries=0;$('playerError').className='dialog hidden';openPlayer(state.channels[state.playing]);};var buttons=$('sections').querySelectorAll('button');for(var i=0;i<buttons.length;i++)buttons[i].onclick=function(){state.section=this.getAttribute('data-section');for(var j=0;j<buttons.length;j++)buttons[j].className='focusable';this.className='focusable active';filter();};}
    function showSources(){var list=load('sources',[]),box=$('sourceList'),i,b;box.innerHTML='';if(!list.length)list=[DEFAULT_URL];for(i=0;i<list.length;i++){b=document.createElement('button');b.className='source-row focusable';b.textContent=list[i];b.onclick=(function(url){return function(){$('sourcesDialog').className='dialog hidden';loadPlaylist(url);};}(list[i]));box.appendChild(b);}$('sourcesDialog').className='dialog';if(box.firstChild)box.firstChild.focus();}
    function registerKeys(){try{var keys=['MediaPlay','MediaPause','MediaStop','MediaFastForward','MediaRewind'];for(var i=0;i<keys.length;i++)tizen.tvinputdevice.registerKey(keys[i]);}catch(e){}}
    function init(){state.showUrls=load('showUrls',false);bind();registerKeys();setInterval(function(){$('clock').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});},1000);var cached=load('channels',[]);if(cached.length){state.channels=cached;buildGroups();filter();}else loadPlaylist(load('lastSource',DEFAULT_URL));$('sections').querySelector('button').focus();}
    window.addEventListener('load',init);
}());
